spring:
  profiles:
    active: dev

---
spring:
  application:
    name: helloserver
  profiles: dev

server:
  port: 8001
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    metadata-map:
      zone: zone-1
  client:
    register-with-eureka: true
    fetch-registry: true
    prefer-same-zone-eureka: true
    #地区
    region: beijing
    availability-zones:
      beijing: zone-1,zone-2
    service-url:
      zone-1: http://localhost:10000/eureka/
      zone-2: http://localhost:10001/eureka/

zone:
  name: zone1

