server:
  port: 8007
logging:
  level:
    root: WARN
    org.springframework: INFO
    org.springframework.cloud: INFO
    org.springframework.interation: INFO
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

    publisher-confirms: true
  cloud:
    stream:
      binders:
        rabbit1:
          type: rabbit

          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest

                publisher-confirms: true
      bindings:
        input:
          binder: rabbit1
          destination: things1
        output:
          binder: rabbit1
          destination: things1
