spring:
  datasource:
    url:  jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
  application:
    name: hystrix-demo
server:
  port: 8003

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/


management:
  endpoints:
    web:
      exposure:
        include: "*"