spring:
  application:
    name: consumer
server:
  port: 8084
eureka:
  instance:
    prefer-ip-address: true
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    metadata-map:
      zone: zone-1
  client:
    register-with-eureka: true
    fetch-registry: true
    prefer-same-zone-eureka: true
    #地区
    region: hangzhou
    availability-zones:
      hangzhou: zone-1,zone-2
    service-url:
      zone-1: http://localhost:10000/eureka/
      zone-2: http://localhost:10001/eureka/

